### ISSUE TITLE
Use H.264 codec to record videos

### ISSUE THREAD

**Issue by brenocrs** [KyleKun/one_second_diary#10]
Description:
Use H.264 codec and not HEVC to generate videos

Reason:
When trying to access the videos on other platforms like windows 10, the HEVC codec is not native as well as paid.

Functionality:

- [ ] Use H.264 codec to record videos

**Comment by KyleKun** [comment]
Can you elaborate a little more on this one?

I've had no issues playing the generated video on Windows 10 so far.

**Comment by brenocrs** [comment]
Here when i tried to open a video using the windows 10 native app "photos" (or the video editor inside the app), i have a warning saying that the video coded [HEVC (H.265) is not supported natively](https://answers.microsoft.com/en-us/windows/forum/all/how-can-i-get-hevc-to-play-on-windows-10/c503b8c0-fdca-4e1f-b822-990977bc864a).
In another issue you told me that you are using ffmpeg to compile the videos right ? im not a flutter dev, but googling i found that is [possible to convert H.265 to H.264 using ffmpeg](https://superuser.com/questions/1380946/how-do-i-convert-10-bit-h-265-videos-to-h-264-without-quality-loss), with a little loss of quality.

is this possible using the ffmpeg in flutter ?

**Comment by KyleKun** [comment]
Interesting, I opened with its default app as well and got no error... Maybe different versions? Try checking if there's any updates for the photos app. 

Anyways, there are two problems with this conversion:

1) Quality loss (I don't feel like adding a lossy option would be used by anyone if you can choose)

2) HEVC supports HDR but H.264 doesn't. I'm not really sure if flutter camera package makes use of it but there's an incoming rewrite of the entire plugin so it's likely it will make use of HDR when available

**Comment by KyleKun** [comment]
Video processing now uses ffmpeg libx264, quality didn't seem to be impacted. Closing as completed.
