### ISSUE TITLE
📌 Handling GeoTagging with bad internet connectivity (`An error occurred while trying to get your location. Please try adding a custom locale manually.`)

### ISSUE THREAD

**Issue by alexanderadam** [KyleKun/one_second_diary#103]
Sometimes I have to try four times so that geo tagging works.
So maybe it would be possible to retry a few times or to do more retries (i.e. 10 with a second pause in between)?

**Comment by KyleKun** [comment]
Will take a look into it.

**Comment by KyleKun** [comment]
There are a couple places in the code this could happen @alexanderadam, is this the message that appears to you?
#### An error occurred while trying to get your location. Please try adding a custom locale manually.

**Comment by alexanderadam** [comment]
I can't remember correctly but I think that's it.
I didn't happen for a few days now.

**Comment by KyleKun** [comment]
> I can't remember correctly but I think that's it. I didn't happen for a few days now.

I've been trying as well and it doesn't occur, if you can force this to happen please go to Settings > Contact > Send Logs, it will help me out.

**Comment by alexanderadam** [comment]
I will! :+1:

**Comment by alexanderadam** [comment]
I just sent you the logs but I already checked and this is the relevant bit:

```
[INFO]: [Geolocation] - Getting location...
[ERROR] : [Geolocation] - Failed to decode location: PlatformException(IO_ERROR, A network error occurred trying to lookup the supplied coordinates (latitude: 12.34567 longitude: 12.34567)., null, null)
Stacktrace: package:one_second_diary/utils/utils.dart 51 in Utils.logError
```

So it's probably just the missing location name lookup, right?

Is there a background queue that could add this later on or so?

And maybe the coordinates could be stored anyway, even if the name couldn't be resolved?

Or do you have better ideas regarding this issue?

**Comment by KyleKun** [comment]
Thanks!

Yes, it's the location decoding, it seems like a [rate limit from Android itself](https://github.com/Baseflow/flutter-geocoding/issues/57#issuecomment-902905040). 

When this happens, tapping again the checkbox to try again works? If the answer yes, maybe trying to decode again a couple more times if it fails with 1 or 2 seconds intervals might solve the problem.

> And maybe the coordinates could be stored anyway, even if the name couldn't be resolved?

It's a good "last scenario" option, however the video won't have the text which is the main point. But there seems to be no other ways to decode without relying on external APIs, and I prefer to avoid that.

**Comment by alexanderadam** [comment]
> When this happens, tapping again the checkbox to try again works? If the answer yes, maybe trying to decode again a couple more times if it fails with 1 or 2 seconds intervals might solve the problem.

Yes, so far it worked every time.

> It's a good "last scenario" option, however the video won't have the text which is the main point. But there seems to be no other ways to decode without relying on external APIs, and I prefer to avoid that.

I get that, but this features requires internet, right? And not having connection is a valid scenario, too, no?

Storing it and resolving it later, when there's internet again, might be a fix for that. Right?

**Comment by KyleKun** [comment]
I'm not sure about it, I think it would be better to have a more robust edit video page in the future where you could select from saved locales or pick from the map and then see the edit happening than trying to do video processing on the background, the UI would likely freeze on less powerful devices, what do you think? Moreover if tapping again works, the retry I am implementing might solve it for good.

**Comment by alexanderadam** [comment]
>  it would be better to have a more robust edit video page in the future where you could select from saved locales or pick from the map

I see. Yeah, that would be good.

> the retry I am implementing might solve it for good.

That's true. Let's try it :+1:

**Comment by alexanderadam** [comment]
How about this: the coordinates will be stored either way but if the name is missing, there's another button for "Fetch location name". This way no background queue is needed and the user still gets all the data if needed.

**Comment by KyleKun** [comment]
I believe it was fixed with retry attempts implementation so I will be closing for now, please reopen if it happens after the update. Thanks!

**Comment by alexanderadam** [comment]
I don't think that it'll conceptually work.

But when will the new version be published?

**Comment by KyleKun** [comment]
Very soon.

**Comment by alexanderadam** [comment]
Just in case this will still be an issue later on if there's no internet connectivity, I still think that [this approach](https://github.com/KyleKun/one_second_diary/issues/103#issuecomment-1753831988) might work best:

On the video view where the "Delete video" and "Add subtitles" buttons are, there could be a "Resolve Geotagging" button in case the metadata (and therefore the text) is missing.

That way no queue is needed and people can simply resolve the coordinates later when they have internet connectivity again.
