### ISSUE TITLE
error when trying to store video

### ISSUE THREAD

**Issue by alexanderadam** [KyleKun/one_second_diary#15]
```
Error saving video! Please try again. If the problem persists, contact the developer.

Error: PlatformException (video_processing_failed, video processing is failed. , null, null)
```

![Error saving video! Please try again. If the problem persists, contact the developer. Error: PlatformException (video_processing_failed, video processing is failed. , null, null)](https://user-images.githubusercontent.com/372620/159185433-5125b29f-60be-43fc-8fa2-cc18a1ae9d26.png)

**Comment by KyleKun** [comment]
Hi @alexanderadam, thanks for reporting this problem! What is the device model and android version?

**Comment by alexanderadam** [comment]
Samsung S20 FE
Android 12 / One UI 4.0
Kernel 4.19.113

**Comment by alexanderadam** [comment]
When this happens I record another video and the second video usually works.
So maybe it's worth doing a retry within the saving method?

**Comment by lubarog13** [comment]
Have the same error
_Oppo A91
Android 11
Kernel 4.14.186_

**Comment by KyleKun** [comment]
Video processing now uses ffmpeg instead of tapioca. Also, a new storage permission was added, so this should be fixed in next version. Please feel free to re-open if it still happens.
