### ISSUE TITLE
support for profiles

### ISSUE THREAD

**Issue by alexanderadam** [KyleKun/one_second_diary#18]
I just had an interesting chat with someone and she had a very good though:

What if you want to create a dedicated one-second-diary for someone else (i.e. to document the development of your child) or if you want to create some contextual diary?

It would be useful to have a dedicated profile to switch to (maybe create the videos on another subdirectory).

I found this suggestion very interesting and thought this would be worth a feature ticket.

A profile switch should only be available if profiles were created in the settings, though.
Otherwise everything should stay as it is. 

Thank you for your work! 🙏

**Comment by KyleKun** [comment]
Implemented by #50 and finished in #52, should be available later today in 1.5.0 beta-1. 
@alexanderadam could you kindly help us to test the apk when it's available? Thanks!!
