### ISSUE TITLE
optional manual/automatic Geotagging

### ISSUE THREAD

**Issue by alexanderadam** [KyleKun/one_second_diary#20]
Similar to this video:

https://youtu.be/bEBWJnqzgU0

There are some captions for places like Spain

**Comment by alexanderadam** [comment]
Any idea when this might be released?

**Comment by KyleKun** [comment]
> @KyleKun any idea when this might be released?

Probably in January since Play Store review can take a while, but I'll try to get a new apk released here by next week so we can start the year with a brand new version 😁
