### ISSUE TITLE
Set time for notifications?

### ISSUE THREAD

**Issue by SXPorrata** [KyleKun/one_second_diary#21]
Great app, simple and clean. 

Not sure if Android allows this, but being able to set the time for the reminder/notification would be great.  It currently does it at around 8/9pm EST and I'm being boring then lol

**Comment by KyleKun** [comment]
> Great app, simple and clean. 
> 
> Not sure if Android allows this, but being able to set the time for the reminder/notification would be great.  It currently does it at around 8/9pm EST and I'm being boring then lol

Thanks! Great idea, I'll add to the list of features coming in the next version.
