### ISSUE TITLE
Extra text in Share link

### ISSUE THREAD

**Issue by edgfowler** [KyleKun/one_second_diary#5]
Share link did not land cleanly on Play Store.  Removing all text before "https:" corrects issue.

![Screenshot 2021-04-19 094840](https://user-images.githubusercontent.com/46655680/115265503-86dc9700-a0f4-11eb-9f2d-e8c2d4942bef.png)

So far, I've only run in VS Code (android-x64-emulator) on windows 10.

**Comment by KyleKun** [comment]
Hey, I'm closing this since this is not an issue, when sharing on phones you usually send it by some messaging app or e-mail, so the link will be clickable anyways. Thanks!
