### ISSUE TITLE
Move clip to another date (New Years Eve feature)

### ISSUE THREAD

**Issue by alexanderadam** [KyleKun/one_second_diary#57]
Soooo I wish you a happy new year. :tada: 

I just recorded a clip to after 0:00 with the celebration of the new year.
One Second Diary stored it for the 01.01. but mentally it belongs to the 31.12. for me because I didn't went to bed yet when I took it. :laughing: 

So I thought that I could simply rename the file name of the clip. However, when I took the clip of today (01.01.) One Second Diary thought that there's already a video existing. So I guess there's still a reference in a SQLite database or so?

Anyway, I would just love to have a possibility to properly move a clip into another date.
Same things could happen when travelling across time zones or so.

Please ask in case I didn't explain it properly.

**Comment by KyleKun** [comment]
> Soooo I wish you a happy new year. :tada: 
> 
> I just recorded a clip to after 0:00 with the celebration of the new year.
> One Second Diary stored it for the 01.01. but mentally it belongs to the 31.12. for me because I didn't went to bed yet when I took it. :laughing: 
> 
> So I thought that I could simply rename the file name of the clip. However, when I took the clip of today (01.01.) One Second Diary thought that there's already a video existing. So I guess there's still a reference in a SQLite database or so?
> 
> Anyway, I would just love to have a possibility to properly move a clip into another date.
> Same things could happen when travelling across time zones or so.
> 
> Please ask in case I didn't explain it properly.

Happy new year!!

The date is rendered on top of the video with ffmpeg, so it's not possible to edit it. 

If you also have a video recorded with default camera app, you can wait for the upload feature to land and then add the video from gallery, replacing your current video. 

If not, I think the best option is to remove the date with another video editing tool and then do the same process above.

In last case you could leave the date wrong for this one and just change the name of the file like you said 😁

**Comment by alexanderadam** [comment]
I don't really care about the displayed date in the video but are there any issues since OneSecondDiary wanted to _edit_ the video instead of recording a new one although I renamed the file.
Hence I guess there's something stored somewhere?
Will it interfere somehow?

**Comment by KyleKun** [comment]
> I don't really care about the displayed date in the video but are there any issues since OneSecondDiary wanted to _edit_ the video instead of recording a new one although I renamed the file.
> Hence I guess there's something stored somewhere?
> Will it interfere somehow?

No, you can record a new one for today normally, even if it shows edit. If you renamed the file and there's no "2023-01-01.mp4" in the folder, nothing will be deleted.

**Comment by alexanderadam** [comment]
I'm not sure whether it's related but I can't create a movie any more although the directory is full of clips 
![Screenshot_20230101_230113](https://user-images.githubusercontent.com/372620/210185962-fa97e9eb-6e8a-472c-9c7a-9130de603af2.png)

**Comment by KyleKun** [comment]
I am closing this one since it was resolved, let's move this last issue discussion also to #55 and concentrate efforts there!
