### ISSUE TITLE
[Subtitles] Unrecognized characters in Ukrainian language

### ISSUE THREAD

**Issue by inbalboa** [KyleKun/one_second_diary#62]
Hi!
Some Ukrainian letters look like this in the subtitles (the word is "Україні").

![uk](https://user-images.githubusercontent.com/2811912/214548073-30084861-47df-41c4-8059-389784d460f1.png)

Version 1.5.0, Android 11.

Thank you for the app!

**Comment by KyleKun** [comment]
> Hi!
> Some Ukrainian letters look like this in the subtitles (the word is "Україні").
> 
> ![uk](https://user-images.githubusercontent.com/2811912/214548073-30084861-47df-41c4-8059-389784d460f1.png)
> 
> Version 1.5.0, Android 11.
> 
> Thank you for the app!

Hey, thanks for reporting, will try to fix it asap!
