### ISSUE TITLE
Unable to toggle geotagging on MIUI

### ISSUE THREAD

**Issue by WPum** [KyleKun/one_second_diary#63]
MIUI 12, both the system location service and the app permission are turned on

When toggling on geotagging, it says "An error occurred while trying to get your location".

**Comment by KyleKun** [comment]
Thanks for reporting, I'll take a look at it.

**Comment by KyleKun** [comment]
Hey @WPum, just to know, does this works for you now?

**Comment by WPum** [comment]
Yes it works. It may have something to do with Google Service Framework.
