### ISSUE TITLE
Standalone video editor

### ISSUE THREAD

**Issue by rancidfrog** [KyleKun/one_second_diary#64]
Have you thought of making a standalone video editor, as open source video editors have been neglected as of late.

![Video editor](https://raw.githubusercontent.com/KyleKun/one_second_diary/main/media/2.jpg)

**Comment by KyleKun** [comment]
Hi @rancidfrog, thanks for the suggestion, but in the moment I am focusing in other projects and a video editor would require a lot of work to have even half of features it should. Please don't mind I'll be closing this since it's not related to One Second Diary itself. Thank you!
