### ISSUE TITLE
Persistent notification

### ISSUE THREAD

**Issue by ShimonHoranek** [KyleKun/one_second_diary#66]
A notification that you couldn't dismiss unless you already recorded a video that day. I always forget about this app and this would be a great reminder. The current notification appears only at set time and you might miss the cool stuff in your day.

**Comment by KyleKun** [comment]
> A notification that you couldn't dismiss unless you already recorded a video that day. I always forget about this app and this would be a great reminder. The current notification appears only at set time and you might miss the cool stuff in your day.

I'll take a look at implementing it, thanks for the suggestion!
