### ISSUE TITLE
Is this app on Apple Store?

### ISSUE THREAD

**Issue by weiddeng** [KyleKun/one_second_diary#82]
Hi KyleKun, thanks for the work! I am wondering is this app available on apple store? I see there is an ios folder. Thank you very much!

**Comment by KyleKun** [comment]
> Hi KyleKun, thanks for the work! I am wondering is this app available on apple store? I see there is an ios folder. Thank you very much!

Hi, thanks! Unfortunately not yet, please see my previous answer here: https://github.com/KyleKun/one_second_diary/discussions/65#discussioncomment-4892521
