### ISSUE TITLE
remember last settings

### ISSUE THREAD

**Issue by alexanderadam** [KyleKun/one_second_diary#83]
For instance which camera was used (front or back) and whether to use geotagging (I always want it!)

**Comment by KyleKun** [comment]
Will be available in next version. Thanks!

**Comment by alexanderadam** [comment]
This still doesn't work.

The app is still using the back camera by default.

**Comment by KyleKun** [comment]
> This still doesn't work.
> 
> The app is still using the back camera by default.

It's in v1.5.3 (which I didn't publish 😅), will be in v1.6 in a couple days.
