### ISSUE TITLE
Default clip length

### ISSUE THREAD

**Issue by akusel** [KyleKun/one_second_diary#84]
Thanks a lot for providing an open source alternative for video journaling! I've just discovered the app and it looks great. I just would humbly like to make a few feature suggestions:

- I love the ability to include clips as long as 10 s in my movie, if I want to. But for people like me, who normally want to record a video clip of a certain length every day, it might be useful to be able to set a default clip length.
(Edit: Added individual issues for each feature.)

Again, thank you very much for doing this. I hope my suggestions don't sound too overbearing.

**Comment by KyleKun** [comment]
Hi @akusel , thank you for the feedback!
I agree with all the points, would only like to request that you create an issue for each one, so it can be tracked separately. 

Please edit the title and content of this with your first point, and create the remaining ones. Thank you!

**Comment by KyleKun** [comment]
I added quick trim buttons and it's really practical, I think it's always better to extend the trimming slider to its full possibility to avoid other kinds of problems, so I will be closing this for now. Trimming should be more precise and easy on the next version. Please re-open if you still think it's valid to implement a default trim after the update. Thanks!
