### ISSUE TITLE
Allow recording in portrait format

### ISSUE THREAD

**Issue by brenocrs** [KyleKun/one_second_diary#9]
Description:
Allow recording of daily records in portrait format

Reason:
Today most people who intend to record daily records use social networks such as tiktok, instagram reals/stories/igtv or youtoube stories, which use the portrait format, which when posted using the landscape format, is very small, making it impracticable.
In case the requirement for recording in landscape is due to some design of the application, it would be interesting to create two "buckets" in the directory "onesecconddiary", where only the videos in landscape are recorded in one, and the other in portrait.

Functionality:

- [ ] Allow recording of daily records in portrait format

**Comment by KyleKun** [comment]
Related to #8 

We need to find a way to compile videos with different properties fast and without losing quality.
