### ISSUE TITLE
Trigger recording with volume buttons

### ISSUE THREAD

**Issue by stephanfriedrich** [KyleKun/one_second_diary#90]
Hi, thanks for this great openSource app.

It would be nice if you could change or extend the record button to trigger videos via the volume buttons for example.
For videos in landscape mode it would be useful to not break your fingers .

what do you think ?
Thx a lot

**Comment by KyleKun** [comment]
I think it's valid, shall be implemented!

**Comment by KyleKun** [comment]
Will be available in next version.

**Comment by codeinabox** [comment]
Has this version been released yet? I'm using version 1.5.2 on a Pixel 8 and I can't trigger recording with the volume buttons
