### ISSUE TITLE
Deleting video from calendar doesn't work

### ISSUE THREAD

**Issue by doubleteapot** [KyleKun/one_second_diary#91]
If you delete a video from your calendar and then immediately replace it with another video it works. But if you don't have one to replace it with it reappears when you change to a different day and then back to the original day. So I have a video at the start of my movie that I can't delete now that was saved in error.

Edit: for some reason when I came back the next day I was able to delete the unwanted video. But I have had this same issue before as well, so I wonder if it only has issues deleting it when the video clip has just been saved?

**Comment by KyleKun** [comment]
I made some changes to video deletion and MediaStore, should be fixed in next version (it always gets deleted correctly now from my tests). Please re-open if the issue persists. Thanks!
