### ISSUE TITLE
Issues adjusting trim edges

### ISSUE THREAD

**Issue by doubleteapot** [KyleKun/one_second_diary#92]
In calendar mode I find it really hard to grab the trim edge target, particularly when the default 10sec trim takes up the whole video so the outer trim edges are on the far edges of the screen (sorry not sure how best to explain). I find it very finicky to try and select a 1 second clip from my daily video of choice, mucking around with the trimming tool (and then as was raised in another topic, after I click save the final video ends up trimming itself even shorter than the 1 second I had selected). Really appreciate that you are providing an ad free, open source app though, thanks!

**Comment by KyleKun** [comment]
Thanks @doubleteapot , trimmer has this and other problems indeed (#77), I will work on it.
