### ISSUE TITLE
Newer days don't show date, fix to show dates

### ISSUE THREAD

**Issue by veritasestmoi** [KyleKun/one_second_diary#96]
I constantly forget to post on there everyday, so there will be a time where I upload a week's clips up there. 

However the newer days only display weekdays as in "Thursday " "Wednesday".... 

I really hope there can be the date behind it thank you!

**Comment by KyleKun** [comment]
Hi @veritasestmoi , I am not sure if I understand this, could you elaborate and/or add a screenshot please? Thanks!

**Comment by veritasestmoi** [comment]
I'm a person who look at dates and never memorize the days of the week. 
I hope all the time indicator can show dates.

My problem: 
So for these couple of days it will show as week days, like this:
![Screenshot_20230829_004937_Media](https://github.com/KyleKun/one_second_diary/assets/68550874/b60b09d7-e3e4-47c2-ae95-6ac1dd36b555)

And for earlier dates it will show weekdays and dates (which is the desired output)
![Screenshot_20230829_005114_Media](https://github.com/KyleKun/one_second_diary/assets/68550874/ac659e63-e0a3-44a0-9ad6-3280a3a0b6f9)

(*^ω^*) Thanks! Hope this make sense

**Comment by KyleKun** [comment]
> I'm a person who look at dates and never memorize the days of the week. 
> I hope all the time indicator can show dates.
> 
> My problem: 
> So for these couple of days it will show as week days, like this:
> ![Screenshot_20230829_004937_Media](https://github.com/KyleKun/one_second_diary/assets/68550874/b60b09d7-e3e4-47c2-ae95-6ac1dd36b555)
> 
> And for earlier dates it will show weekdays and dates (which is the desired output)
> ![Screenshot_20230829_005114_Media](https://github.com/KyleKun/one_second_diary/assets/68550874/ac659e63-e0a3-44a0-9ad6-3280a3a0b6f9)
> 
> (*^ω^*) Thanks! Hope this make sense 

Got it now, thank you!
This is an Android system dialog so not sure if I can customize what it shows, but maybe it's possible to show only media that matches the selected date. I'll take a look into it.

**Comment by KyleKun** [comment]
Didn't find anything about if such customization is possible, but the new experimental picker supports filtering recordings by date, so it will show the recordings for the desired date always on top. Hope that helps!
