### ISSUE TITLE
Auto skip to current date (back in time)

### ISSUE THREAD

**Issue by veritasestmoi** [KyleKun/one_second_diary#99]
I always forget to upload videos so I will constantly need to go back in time to post it.

However, I found the system will not automatically jump to the date I'm currently adding.

**Current output**
 I'm adding a post on 8/24, but the gallery will not show videos from that date on the top, only from today 9/2)

**Desired output:** 
 I'm adding a post on 8/24, the gallery will show 8/24 videos and pictures at the top.

Thank you!!!!!!!!!!!!

**Comment by KyleKun** [comment]
Hi @veritasestmoi , that was what I meant in this [comment](https://github.com/KyleKun/one_second_diary/issues/96#issuecomment-1702030820). This was already implemented and will be available for next version 😊
